#ifndef __ICONS__
#define __ICONS__


	//! This file provides all the icons used. 
	//! These are all defined as 16*16 4-byte RGBA values.
	//! \todo Replace these with drawn labels?

// RGBA Red Opaque - =
#define ZZRE "\xFF\0\0\xFF"
// RGBA Yellow Opaque - 
#define ZZYL "\xFF\xFF\0\xFF"
// RGBA White opaque - @
#define ZZWH "\xFF\xFF\xFF\xFF"
// RGBA Green opaque - +
#define ZZGN "\00\xFF\00\xFF"
// RGBA Black - #
#define ZZBK "\0\0\0\xFF"
// RGBA Mid Cyan - |
#define ZZCY "\0\xE0\xE0\xFF"
// RGBA Blue opaque
#define ZZBL "\00\00\xFF\xFF"
// RGBA Transparent (no character)
#define ZZBG "\0\0\0\0"

//! Icon "Download eQSL.cc".
	const unsigned char ICON_DL_EQSL[] =
		/* Download eQSL | - dark blue, # - black
		0           ###  ;
		1       || #   # ;
		2  ###  || #   # ;
		3 #   # || #   # ;
		4 ####  || #   # ;
		5 #     || #  ## ;
		6  ###  ||  #### ;
		7       ||       ;
		8 |###  || #  || ;
		9 #|| # || # ||  ;
		0 # ||  || #||   ;
		1  ###| || #|    ;
		2     #|||||     ;
		3 #   #||||#     ;
		4  ###  || ##### ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZCY ZZCY ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZCY ZZCY ZZBK ZZBK ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZCY ZZCY ZZWH
		ZZWH ZZBK ZZCY ZZCY ZZWH ZZBK ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZCY ZZCY ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZCY ZZCY ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZCY ZZCY ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZCY ZZWH ZZCY ZZCY ZZWH ZZBK ZZCY ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZCY ZZCY ZZCY ZZCY ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZCY ZZCY ZZCY ZZCY ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	//! Icon "Download Logbook of the World"
	const unsigned char ICON_DL_LOTW[] =
		/* Download LotW | - dark blue, # - black
		0 #              ;
		1 #     ||       ;
		2 #     ||  ###  ;
		3 #     || #   # ;
		4 #     || #   # ;
		5 #     || #   # ;
		6 ##### ||  ###  ;
		7       ||       ;
		8 ||    || #  |# ;
		9 #||   || # ||# ;
		0 # ||  || #|| # ;
		1 ###|| || #|# # ;
		2 #   |||||# # # ;
		3 #    ||||# # # ;
		4  #### ||  # #  ;
		5                ;
		*/
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH ZZCY ZZCY ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZCY ZZCY ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZBK ZZCY ZZBK ZZWH
		ZZWH ZZBK ZZCY ZZCY ZZWH ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZWH ZZBK ZZCY ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZCY ZZCY ZZWH ZZWH ZZCY ZZCY ZZWH ZZBK ZZCY ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZCY ZZCY ZZWH ZZCY ZZCY ZZWH ZZBK ZZCY ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZCY ZZCY ZZCY ZZCY ZZCY ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZCY ZZCY ZZCY ZZCY ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH ZZCY ZZCY ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	//! Icon "New QSO"
	const unsigned char ICON_NEW_QSO[] =
		/* New Record @ = white
		0 @@@@@@@@@@@@@@@@
		1 @@@@@@@@@@@@@@@@
		2 @@@@@@@@@@@@@@@@
		3 @@@          @@@
		4 @@@          @@@
		5 @@@          @@@
		6 @@@          @@@
		7 @@@          @@@
		8 @@@          @@@
		9 @@@          @@@
		0 @@@          @@@
		1 @@@          @@@
		2 @@@          @@@
		3 @@@@@@@@@@@@@@@@
		4 @@@@@@@@@@@@@@@@
		5 @@@@@@@@@@@@@@@@
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	//! Icon "Save QSO"
	const unsigned char ICON_SAVE_QSO[] =
		/* New Record @ = white, + = green
		0 @@@@@@@@@@@@@@@@
		1 @@@@@@@@@@@@@@@@
		2 @@@@@@@@@@@@@@@@
		3 @@@          @@@
		4 @@@        ++@@@
		5 @@@       ++ @@@
		6 @@@      ++  @@@
		7 @@@ +   ++   @@@
		8 @@@ ++ ++    @@@
		9 @@@  +++     @@@
		0 @@@   +      @@@
		1 @@@          @@@
		2 @@@          @@@
		3 @@@@@@@@@@@@@@@@
		4 @@@@@@@@@@@@@@@@
		5 @@@@@@@@@@@@@@@@
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZGN ZZGN ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZGN ZZGN ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZGN ZZGN ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZGN ZZBG ZZBG ZZBG ZZGN ZZGN ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZGN ZZGN ZZBG ZZGN ZZGN ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZGN ZZGN ZZGN ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZGN ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	//! Icon "Cancel QSO"
	const unsigned char ICON_CNCL_QSO[] =
		/* New Record @ = white, = = green
		0 @@@@@@@@@@@@@@@@
		1 @@@@@@@@@@@@@@@@
		2 @@@@@@@@@@@@@@@@
		3 @@@==      ==@@@
		4 @@@===    ===@@@
		5 @@@ ===  === @@@
		6 @@@  ======  @@@
		7 @@@   ====   @@@
		8 @@@   ====   @@@
		9 @@@  ======  @@@
		0 @@@ ===  === @@@
		1 @@@===    ===@@@
		2 @@@==      ==@@@
		3 @@@@@@@@@@@@@@@@
		4 @@@@@@@@@@@@@@@@
		5 @@@@@@@@@@@@@@@@
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZRE ZZRE ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZRE ZZRE ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZBG ZZBG ZZBG ZZBG ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZRE ZZRE ZZRE ZZBG ZZBG ZZRE ZZRE ZZRE ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZRE ZZRE ZZRE ZZRE ZZRE ZZRE ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZRE ZZRE ZZRE ZZRE ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZRE ZZRE ZZRE ZZRE ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZRE ZZRE ZZRE ZZRE ZZRE ZZRE ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZRE ZZRE ZZRE ZZBG ZZBG ZZRE ZZRE ZZRE ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZBG ZZBG ZZBG ZZBG ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZRE ZZRE ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZRE ZZRE ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	//! Icon "Delete QSO"
	const unsigned char ICON_DEL_QSO[] =
		/* New Record @ = white, # = black
		0 ##@@@@@@@@@@@@##
		1 ###@@@@@@@@@@###
		2 @###@@@@@@@@###@
		3 @@###      ###@@
		4 @@@###    ###@@@
		5 @@@ ###  ### @@@
		6 @@@  ######  @@@
		7 @@@   ####   @@@
		8 @@@   ####   @@@
		9 @@@  ######  @@@
		0 @@@ ###  ### @@@
		1 @@@###    ###@@@
		2 @@###      ###@@
		3 @###@@@@@@@@###@
		4 ###@@@@@@@@@@###
		5 ##@@@@@@@@@@@@##
		*/
		ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK
		ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK
		ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZBG ZZBG ZZBG ZZBG ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBK ZZBK ZZBK ZZBG ZZBG ZZBK ZZBK ZZBK ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBK ZZBK ZZBK ZZBK ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBK ZZBK ZZBK ZZBK ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBK ZZBK ZZBK ZZBG ZZBG ZZBK ZZBK ZZBK ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZBG ZZBG ZZBG ZZBG ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH
		ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK
		ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK
		;

	//! Icon "Retime QSO"
	const unsigned char ICON_RETIME_QSO[] =
		/* New Record @ = white, + = blue
		0 @@@@@@@@@@@@@@@@
		1 @@@@@@@@@@@@@@@@
		2 @@@@@@@@@@@@@@@@
		3 @@@          @@@
		4 @@@          @@@
		5 @@@  ++   ++ @@@
		6 @@@  ++   ++ @@@
		7 @@@++++ + ++ @@@
		8 @@@++++ + ++ @@@
		9 @@@  ++   ++ @@@
		0 @@@  ++   ++ @@@
		1 @@@          @@@
		2 @@@          @@@
		3 @@@@@@@@@@@@@@@@
		4 @@@@@@@@@@@@@@@@
		5 @@@@@@@@@@@@@@@@
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBL ZZBG ZZBG ZZBG ZZBG ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBL ZZBG ZZBG ZZBG ZZBG ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBL ZZBG ZZBG ZZBG ZZBG ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBG ZZBL ZZBG ZZBL ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBG ZZBL ZZBG ZZBL ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBL ZZBG ZZBG ZZBG ZZBG ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBL ZZBG ZZBG ZZBG ZZBG ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBL ZZBG ZZBG ZZBG ZZBG ZZBG ZZBL ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZBG ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;


	const unsigned char ICON_EXTR_EQSL[] =
		/* Upload eQSL | - dark blue, # - black
		0           ###  ;
		1          #   # ;
		2  ### ||||#   # ;
		3 #   ||  ||   # ;
		4 ####||  ||   # ;
		5 #      ||#  ## ;
		6  ###  ||  #### ;
		7       ||       ;
		8  ###     #     ;
		9 #   # || #     ;
		0 #     || #     ;
		1  ###     #     ;
		2     #    #     ;
		3 #   #    #     ;
		4  ###     ##### ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZBL ZZBL ZZBL ZZBL ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBK ZZWH ZZWH ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_EXTR_LOTW[] =
		/* Upload LotW | - dark blue, # - black
		0 #              ;
		1 #              ;
		2 #    |||| ###  ;
		3 #   ||  ||   # ;
		4 #   ||  ||   # ;
		5 #      ||#   # ;
		6 ##### ||  ###  ;
		7       ||       ;
		8          #   # ;
		9 #     || #   # ;
		0 #     || #   # ;
		1 ###      # # # ;
		2 #        # # # ;
		3 #        # # # ;
		4  ####     # #  ;
		5                ;
		*/
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH ZZBL ZZBL ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_EXTR_CLOG[] =
		/* Upload LotW | - dark blue, # - black
		0                ;
		1                ;
		2      ||||      ;
		3     ||  ||     ;
		4     ||  ||     ;
		5  ###   || #    ;
		6 #      || #    ;
		7 #     ||  #    ;
		8 #         #    ;
		9  ###  ||  #### ;
		0       ||       ;
		1                ;
		2                ;
		3                ;
		4                ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZBL ZZBL ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_UPLOAD[] =
		/*
		0                ;
		1                ;
		2       ||       ;
		3      ||||      ;
		4     ||||||     ;
		5    || || ||    ;
		6   ||  ||  ||   ;
		7  ||   ||   ||  ;
		8       ||       ;
		9       ||       ;
		0       ||       ;
		1       ||       ;
		2       ||       ;
		3                ;
		4                ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZBL ZZBL ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_MAP[] =
		/*
		Google maps: # - Black, | - blue, = - green
		5                ;
		0     ######     ;
		1    #||||=|#    ;
		2   #|||=|=||#   ;
		3  #||||||=|==#  ;
		4 #|||||=======# ;
		5 #|||||=======# ;
		6 #|||||=======# ;
		7 #||||==||====# ;
		8 #||||==||=|==# ;
		9 #||||||||||||# ;
		0  #||===|||||#  ;
		1   #=======|#   ;
		2    #======#    ;
		3     ######     ;
		4                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZGN ZZBL ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBK ZZBL ZZBL ZZBL ZZGN ZZBL ZZGN ZZBL ZZBL ZZBK ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZGN ZZBL ZZGN ZZGN ZZBK ZZWH ZZWH
		ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZBL ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZBK ZZWH
		ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZBL ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZBK ZZWH
		ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZBL ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZBK ZZWH
		ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZGN ZZGN ZZBL ZZBL ZZGN ZZGN ZZGN ZZGN ZZBK ZZWH
		ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZGN ZZGN ZZBL ZZBL ZZGN ZZBL ZZGN ZZGN ZZBK ZZWH
		ZZWH ZZBK ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBL ZZBL ZZGN ZZGN ZZGN ZZBL ZZBL ZZBL ZZBL ZZBL ZZBK ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZBK ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZBL ZZBK ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZBK ZZGN ZZGN ZZGN ZZGN ZZGN ZZGN ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_QRZ_COM[] =
		/* QRZ: # - black
		0  ##  ###  #### ;
		1 #  # #  #    # ;
		2 #  # #  #    # ;
		3 #  # ###    #  ;
		4 # ## #  #  #   ;
		5 #  # #  # #    ;
		6  ### #  # #### ;
		7                ;
		8      ##        ;
		9      ##        ;
		0                ;
		1  ##  ##   # #  ;
		2 #   #  # # # # ;
		3 #   #  # # # # ;
		4 #   #  # #   # ;
		5  ##  ##  #   # ;
		*/
		ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZBK ZZBK ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZBK ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZBK ZZBK ZZBK ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH ZZBK ZZWH
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZBK ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH
		;

	const unsigned char ICON_EXTR_ON[] =
		/* Extract on: | = blue
		0                ;
		1                ;
		2      ||||      ;
		3     ||  ||     ;
		4     ||  ||     ;
		5         ||     ;
		6        ||      ;
		7       ||       ;
		8       ||       ;
		9                ;
		0       ||       ;
		1       ||       ;
		2                ;
		3                ;
		4                ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_EXTR_OFF[] =
		/* Extract on: | = blue, & =red
		0&&            &&;
		1&&&          &&&;
		2 &&&  ||||  &&& ;
		3  &&&||  ||&&&  ;
		4   &&||  ||&&   ;
		5    &&&  ||&    ;
		6     &&&||&     ;
		7      &||&      ;
		8      &||&      ;
		9     &&&&&&     ;
		0    &&&||&&&    ;
		1   &&& || &&&   ;
		2  &&&      &&&  ;
		3 &&&        &&& ;
		4&&&          &&&;
		5&&            &&;
		*/
		ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE
		ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE
		ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH
		ZZWH ZZWH ZZRE ZZRE ZZRE ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZRE ZZRE ZZRE ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZRE ZZRE ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZRE ZZRE ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZBL ZZBL ZZRE ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZBL ZZBL ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZBL ZZBL ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZBL ZZBL ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZBL ZZBL ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZBL ZZBL ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH
		ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH
		ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE
		ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE
		;

	const unsigned char ICON_EXTR_DISP[] =
		/* Extract on: | = blue # = black
		0                ;
		1 ###############;
		2      ||||      ;
		3 ####||##||#####;
		4     ||  ||     ;
		5 ########||#####;
		6        ||      ;
		7 ######||#######;
		8       ||       ;
		9 ###############;
		0       ||       ;
		1 ######||#######;
		2                ;
		3 ###############;
		4                ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBL ZZBL ZZBK ZZBK ZZBL ZZBL ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBL ZZBL ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBL ZZBL ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBL ZZBL ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;

	const unsigned char ICON_RIG_ON[] =
		/* Rig connect - # = black
		0                ;
		1                ;
		2                ;
		3 ###############;
		4 #             #;
		5 #             #;
		6 #  #   #   #  #;
		7 # ### ### ### #;
		8 #  #   #   #  #;
		9 #             #;
		0 #             #;
		1 ###############;
		2                ;
		3                ;
		4                ;
		5                ;
		*/
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZBK ZZBK ZZBK ZZWH ZZBK ZZBK ZZBK ZZWH ZZBK ZZBK ZZBK ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH
		;
	const unsigned char ICON_RIG_OFF[] =
		/* Rig connect - # = black
		0&&            &&;
		1&&&          &&&;
		2 &&&        &&& ;
		3 ###############;
		4 # &&&    &&&  #;
		5 #  &&&  &&&   #;
		6 #  #&&&#&& #  #;
		7 # ###&### ### #;
		8 #  # &&#&  #  #;
		9 #   &&&&&&    #;
		0 #  &&&  &&&   #;
		1 ###############;
		2  &&&      &&&  ;
		3 &&&        &&& ;
		4&&&          &&&;
		5&&            &&;
		*/
		ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE
		ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE
		ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZBK ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZRE ZZRE ZZRE ZZBK ZZRE ZZRE ZZWH ZZBK ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZBK ZZBK ZZBK ZZRE ZZBK ZZBK ZZBK ZZWH ZZBK ZZBK ZZBK ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZBK ZZWH ZZRE ZZRE ZZBK ZZRE ZZWH ZZWH ZZBK ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZBK
		ZZWH ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK
		ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH
		ZZWH ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE ZZWH
		ZZRE ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE ZZRE
		ZZRE ZZRE ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZRE ZZRE
		;

	const unsigned char ICON_IMPORT[] =
		/*
		0############    ;
		1#          #    ;
		2############    ;
		3#          #    ;
		4#          #    ;
		5#          #    ;
		6#    |||   #    ;
		7#     |||  #  ||;
		8#      ||| #  ||;
		9#       |||#  ||;
		0#        |||  ||;
		1##########||| ||;
		2           |||||;
		3            ||||;
		4       |||||||||;
		5       |||||||||;
		*/
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZWH ZZWH ZZWH ZZBK ZZWH ZZWH ZZWH ZZWH
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZWH ZZWH ZZBK ZZWH ZZWH ZZBL ZZBL
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZWH ZZBK ZZWH ZZWH ZZBL ZZBL
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBK ZZWH ZZWH ZZBL ZZBL
		ZZBK ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZWH ZZWH ZZBL ZZBL
		ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBK ZZBL ZZBL ZZBL ZZWH ZZBL ZZBL
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZBL
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL
		ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZWH ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL ZZBL
		;
#endif
